dist: focal
language: scala
# Use container-based infrastructure
sudo: false

addons:
  apt:
    packages:
      - ca-certificates-java
    
branches:
  only:
    - master
    - travis

jdk: openjdk9
scala: 2.12.7

before_install:
  - rm "${JAVA_HOME}/lib/security/cacerts"
  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

before_script:
  - unset _JAVA_OPTIONS
  - unset SBT_OPTS
  - export JAVA_TOOL_OPTIONS="-Xmx1548m"
script:
  - sbt -J-Xms128m -J-Xmx1248m -J-XX:+UseConcMarkSweepGC -J-XX:+CMSClassUnloadingEnabled checkPR

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
