dist: focal
language: scala

addons:
  apt:
    packages:
      - ca-certificates-java
    
branches:
  only:
    - master
    - travis

jdk: openjdk11
scala: 2.12.9

before_install:
  - unset _JAVA_OPTIONS
  - unset SBT_OPTS
  - export JAVA_TOOL_OPTIONS="-Xmx1548m"
install:
  - sbt build

before_script:
  - pip install -q -r e2e/requirements.txt
script:
  - sbt testAll
  - behave -f plain --no-timings

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
