language: scala
# Use container-based infrastructure
sudo: false

jdk:
- oraclejdk9
scala:
- 2.12.7
script:
  - unset _JAVA_OPTIONS
  - unset SBT_OPTS
  - export JAVA_TOOL_OPTIONS="-Xmx1548m"
  - sbt -J-Xms128m -J-Xmx1248m -J-XX:+UseConcMarkSweepGC -J-XX:+CMSClassUnloadingEnabled checkPR
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
